--| Monarch Core SQL Schema |--

CREATE TABLE IF NOT EXISTS `users` (
    `userId` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
    `license` VARCHAR(50) DEFAULT NULL,
    `license2` VARCHAR(50) DEFAULT NULL,
    `fivem` VARCHAR(20) DEFAULT NULL,
    `steam` VARCHAR(30) DEFAULT NULL,
    `discord` VARCHAR(30) DEFAULT NULL,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `last_login` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`userId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;