---@class FiveMConnectingDeferrals
---@field handover fun(payload: table)
---@field defer fun()
---@field update fun(message: string)
---@field presentCard fun(card: string, cb?: fun(data: table, rawData: string))
---@field done fun(reason?: string)

---@class DocsType
---@field issued_at string | osdate
---@field expires_at string | osdate | nil

---@class PlayerDB
---@field userLogin fun(identifiers: table, maxCharacters: number): number | false                                      Used to register or update a user during login
---@field getUserSlots fun(userId: number): number | false                                                              Used to get user's character max slots
---@field getUserCharacters fun(userId: number, slots: number): table<number, table>                                    Used to get user's character slots and all their characters
---@field getCharacterBySlot fun(userId: number, slot: number): table                                                   Used to get a character from a precise slot
---@field createCharacter fun(userId: number, slot: number, character: table): number                                   Used to create a new character for a user
---@field getStatus fun(charId: number): table | nil                                                                    Used to get the status of a character
---@field saveStatus fun(charId: number, data: table)                                                                   Used to save the status of a character
---@field getGroups fun(charId: number): table | nil                                                                    Used to get the groups of a character
---@field saveGroup fun(charId: number, slot: number, data: table)                                                      Used to save a group of a character
---@field deleteGroupBySlot fun(charId: number, slot: number)                                                           Used to delete a group using its slot
---@field deleteGroupByName fun(charId: number, name: string)                                                           Used to delete a group of a character
---@field setGrade fun(charId: number, slot: number, grade: number)                                                     Used to set the grade of a character in a group
---@field setDuty fun(charId: number, slot: number, duty: boolean)                                                      Used to set the duty of a character in a group
---@field getMoney fun(charId: number): table | nil                                                                     Used to get the money of a character
---@field saveMoney fun(charId: number, data: table)                                                                    Used to save the money of a character
---@field getDocs fun(charId: number): table                                                                            Used to get the documents of a character
---@field addDoc fun(charId: number, docType: string, expiresAt: string | osdate | nil)                                 Used to add a document to a character
---@field removeDoc fun(charId: number, docType: string)                                                                Used to remove a document from a character

---@class MnrPlayer
---@field __index self
---@field userId number                                                                                                 User ID of the player linked to identifiers
---@field charId number
---@field source number
---@field bio { firstname: string, lastname: string, gender: string, origin: string, birthdate: string } | nil
---@field money { money: number, bank: number, black_money: number } | nil
---@field groups table
---@field docs table<string, DocsType>
---@field status { health: number, armor: number, hunger: number, thirst: number, stress: number } | nil
---@field new fun(userId: number, src: number): self
---@field getSource fun(self: self): number
---@field _loadMoney fun(self: self)
---@field _saveMoney fun(self: self)
---@field _loadGroups fun(self: self)
---@field _saveGroups fun(self: self)
---@field _loadDocs fun(self: self)
---@field _loadStatus fun(self: self)
---@field _saveStatus fun(self: self)
---@field loadChar fun(self: self, character: table)
---@field save fun(self: self)
---@field getMoney fun(self: self, moneyType: string): number
---@field addMoney fun(self: self, moneyType: string, amount: number): boolean
---@field removeMoney fun(self: self, moneyType: string, amount: number): boolean
---@field addGroup fun(self: self, cat: string, name: string, grade: number): boolean, string | nil
---@field setGroup fun(self: self, slot: number, cat: string, name: string, grade: number): boolean, string | nil
---@field getGroup fun(self: self, name: string): table | false, number | nil
---@field getGroupsByCategory fun(self: self, cat: string): table
---@field removeGroup fun(self: self, slot: number): boolean, string | nil
---@field setGrade fun(self: self, slot: number, grade: number): boolean, string | nil
---@field setDuty fun(self: self, slot: number, duty: boolean): boolean, string | nil                                       Used to set player duty
---@field addDoc fun(self: self, docType: string, expiresAt: string): boolean
---@field removeDoc fun(self: self, docType: string): boolean, string | nil
---@field hasDoc fun(self: self, docType: string): boolean
---@field setStatus fun(self: self, name: string, value: number, operator?: '+' | '-'): false | nil                         Used to set a specific field status value (operator can be applied to not get the value before the set)
---@field degradeStatus fun(self: self)                                                                                     Internal function to loop it simulating status decrease

---@class MnrUserIdentifiers
---@field license string
---@field license2 string
---@field fivem string
---@field steam string
---@field discord string